//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAT_UD3_EJ3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public string Medico { get; set; }
        public string horaInic { get; set; }
        public string horaFin { get; set; }
        public string diaSemana { get; set; }
    
        public virtual Medicos Medicos { get; set; }
    }
}
